### ISSUE TITLE
Cannot compile on Ubuntu 14.04

### ISSUE THREAD

**Issue by probonopd** [linuxdeepin/dtkcore#8]
Cannot compile on Ubuntu 14.04:

```
/home/travis/build/probonopd/dtkcore/src/settings/backend/gsettingsbackend.cpp:8:33: fatal error: QGSettings/QGSettings: No such file or directory
 #include <QGSettings/QGSettings>
                                 ^
compilation terminated.
make[1]: *** [gsettingsbackend.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/home/travis/build/probonopd/dtkcore/build/src'
make: *** [sub-src-make_first-ordered] Error 2
The command "make -j$(nproc)" exited with 2.
```

Build steps:
https://github.com/probonopd/dtkcore/blob/1bfd0936df917dedac67bc85a64dec7f549e3f34/.travis.yml

Build log:
https://travis-ci.com/probonopd/dtkcore/jobs/167408099#L575-L582

cc @rekols

**Comment by rekols** [comment]
Need to upgrade qt 5.10 and ubuntu xenial, I have fixed it. 

https://github.com/rekols/dtkcore/blob/master/.travis.yml

**Comment by probonopd** [comment]
Thanks @rekols. Now getting

```
In file included from /opt/qt59/include/QtCore/QObject:1:0,
                 from /home/travis/build/probonopd/dtkcore/src/filesystem/dbasefilewatcher.h:24,
                 from /home/travis/build/probonopd/dtkcore/src/filesystem/dfilewatcher.h:21,
                 from /home/travis/build/probonopd/dtkcore/src/filesystem/dfilewatcher.cpp:18:
/opt/qt59/include/QtCore/qobject.h:313:13: note: template<class Func1, class Func2> static typename std::enable_if<(QtPrivate::FunctionPointer<Func2>::ArgumentCount == (-1)), QMetaObject::Connection>::type QObject::connect(const typename QtPrivate::FunctionPointer<Func>::Object*, Func1, const QObject*, Func2, Qt::ConnectionType)
             connect(const typename QtPrivate::FunctionPointer<Func1>::Object *sender, Func1 signal, const QObject *context, Func2 slot,
             ^
/opt/qt59/include/QtCore/qobject.h:313:13: note:   template argument deduction/substitution failed:
/home/travis/build/probonopd/dtkcore/src/filesystem/dfilewatcher.cpp:113:46: note:   mismatched types ‘const typename QtPrivate::FunctionPointer<Func>::Object*’ and ‘QGlobalStatic<Dtk::Core::DFileSystemWatcher, (* Dtk::Core::{anonymous}::Q_QGS_watcher_file_private::innerFunction), (* & Dtk::Core::{anonymous}::Q_QGS_watcher_file_private::guard)>’
                q, &DFileWatcher::onFileClosed);
                                              ^
make[1]: *** [dfilewatcher.o] Error 1
make[1]: Leaving directory `/home/travis/build/probonopd/dtkcore/build/src'
make: *** [sub-src-make_first-ordered] Error 2
```

Build log:
https://travis-ci.com/probonopd/dtkcore/builds/95927902#L1034-L1048

**Comment by hunt978** [comment]
checkout this one:

https://github.com/linuxdeepin/gsettings-qt

**Comment by probonopd** [comment]
Thank you very much. In the meantime, **xenial** is now the oldest still-supported Ubuntu release.

**Comment by BLumia** [comment]
Hi, sorry for the late reply.

Ubuntu 14.04 is no longer supported by deepin team, so I'll close this issue for now. If people are willing to port it to older Qt version, please feel free to fork it and start hacking, and also feel free to start a discussion at the [developer-center](https://github.com/linuxdeepin/developer-center/) if you need help.

Thanks!
