### ISSUE TITLE
error: no matching function for call to ‘Dtk::Core::DFileWatcher::connect

### ISSUE THREAD

**Issue by GriefNorth** [linuxdeepin/dtkcore#2]
When I build in linux(qt5.6 and 5/9) i have this error 
```
dfilewatcher.cpp:95: error: no matching function for call to ‘Dtk::Core::DFileWatcher::connect(QGlobalStatic<Dtk::Core::DFileSystemWatcher, (* Dtk::Core::{anonymous}::Q_QGS_watcher_file_private::innerFunction), (* & Dtk::Core::{anonymous}::Q_QGS_watcher_file_private::guard)>&, void (Dtk::Core::DFileSystemWatcher::*)(const QString&, const QString&, Dtk::Core::DFileSystemWatcher::QPrivateSignal), Dtk::Core::DFileWatcher* const&, void (Dtk::Core::DFileWatcher::*)(const QString&, const QString&))’
                q, &DFileWatcher::onFileDeleted);
```
But if build with Windows and minGW this doesn't have error
